import { useState, useEffect, useRef } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { GradientButton } from "@/components/ui/gradient-button";

interface LogicPuzzleProps {
  // FIX: added duration param so dashboard records real elapsed time (was hardcoded 180s)
  onGameComplete: (score: number, correct: number, total: number, duration: number, difficultySettings?: any) => void;
  onClose: () => void;
}

interface Puzzle {
  sequence: string[];
  options: string[];
  correctAnswer: string;
  pattern: string;
}

const SHAPES = ["🔴", "🔵", "🟢", "🟡", "🟣", "🟠"];
const EXTRA_SHAPES = ["⭐", "💎", "🔶", "🔷"];

const LOGIC_BEST_KEY = "brainboost_best_logic";

function LogicAnimatedScore({ target }: { target: number }) {
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    const step = Math.ceil(target / 30);
    const iv = setInterval(() => {
      setDisplay(prev => { const n = prev + step; if (n >= target) { clearInterval(iv); return target; } return n; });
    }, 30);
    return () => clearInterval(iv);
  }, [target]);
  return <span>{display}</span>;
}

function LogicResultScreen({ correct, total, onPlayAgain, onClose }: {
  correct: number; total: number; onPlayAgain: () => void; onClose: () => void;
}) {
  const accuracy = Math.round((correct / total) * 100);
  const score = correct * 100;
  const prev = parseInt(localStorage.getItem(LOGIC_BEST_KEY) || "0", 10);
  const isNewBest = score > prev;
  useEffect(() => { if (isNewBest) localStorage.setItem(LOGIC_BEST_KEY, String(score)); }, []);
  const msg = accuracy >= 90 ? "Perfect reasoning! You're a logic master. 🧠" : accuracy >= 70 ? "Solid logic skills! Keep building on this. 💪" : "Logic is a skill — every puzzle makes you sharper. 🌱";

  return (
    <div className="text-center space-y-6 py-4">
      <div className="text-5xl">{accuracy >= 90 ? "🏆" : accuracy >= 70 ? "🧠" : "💪"}</div>
      <div>
        <h3 className="text-2xl font-bold text-primary mb-1">Game Complete!</h3>
        <p className="text-muted-foreground text-sm">{msg}</p>
      </div>
      {isNewBest && (
        <div className="inline-flex items-center gap-2 bg-chart-4/15 text-chart-4 px-4 py-2 rounded-full text-sm font-semibold animate-pulse">
          ⭐ New Personal Best!
        </div>
      )}
      <div className="grid grid-cols-3 gap-3">
        <div className="bg-primary/10 rounded-xl p-4">
          <div className="text-2xl font-bold text-primary"><LogicAnimatedScore target={score} /></div>
          <div className="text-xs text-muted-foreground mt-1">Score</div>
        </div>
        <div className="bg-chart-3/10 rounded-xl p-4">
          <div className="text-2xl font-bold text-chart-3">{correct}/{total}</div>
          <div className="text-xs text-muted-foreground mt-1">Correct</div>
        </div>
        <div className="bg-chart-2/10 rounded-xl p-4">
          <div className="text-2xl font-bold text-chart-2">{accuracy}%</div>
          <div className="text-xs text-muted-foreground mt-1">Accuracy</div>
        </div>
      </div>
      {!isNewBest && prev > 0 && <p className="text-xs text-muted-foreground">Personal best: {prev} pts</p>}
      <div className="flex gap-3 justify-center">
        <GradientButton onClick={onPlayAgain} data-testid="button-restart-logic">
          <i className="fas fa-redo mr-2"></i>Play Again
        </GradientButton>
        <Button variant="outline" onClick={onClose} data-testid="button-back-dashboard-logic">
          Back to Dashboard
        </Button>
      </div>
    </div>
  );
}

export function LogicPuzzle({ onGameComplete, onClose }: LogicPuzzleProps) {
  const [currentPuzzle, setCurrentPuzzle] = useState<Puzzle | null>(null);
  const [currentRound, setCurrentRound] = useState(1);
  const [correctAnswers, setCorrectAnswers] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [gameComplete, setGameComplete] = useState(false);
  const gameStartTimeRef = useRef<number>(Date.now());

  const { data: difficultyData } = useQuery<{
    sequenceLength: number;
    complexityLevel: number;
    totalRounds: number;
  }>({
    queryKey: ['/api/difficulty/logic'],
  });

  const totalRounds = difficultyData?.totalRounds || 8;
  const sequenceLength = difficultyData?.sequenceLength || 4;
  const complexity = difficultyData?.complexityLevel || 1;

  // FIX: Ensure exactly 3 options are always generated by drawing from an expanded pool
  function buildOptions(correctAnswer: string, usedInSequence: string[], pool: string[]): string[] {
    // Wrong options must not equal the correct answer and not already appear in sequence
    const candidates = pool.filter(s => s !== correctAnswer && !usedInSequence.includes(s));
    // Shuffle candidates
    const shuffled = [...candidates].sort(() => Math.random() - 0.5);
    const wrong = shuffled.slice(0, 2);
    // If still short (extremely rare), pad with items from a larger combined pool
    if (wrong.length < 2) {
      const fallbackPool = [...SHAPES, ...EXTRA_SHAPES];
      for (const s of fallbackPool) {
        if (wrong.length >= 2) break;
        if (s !== correctAnswer && !wrong.includes(s)) wrong.push(s);
      }
    }
    return [correctAnswer, ...wrong].sort(() => Math.random() - 0.5);
  }

  const generateShapePattern = (): Puzzle => {
    const allShapes = [...SHAPES, ...EXTRA_SHAPES];
    const patternLength = Math.min(sequenceLength, SHAPES.length - 1);

    const patterns = [
      // Repeating pattern
      () => {
        const baseLength = Math.max(2, Math.floor(patternLength / 2));
        const base = SHAPES.slice(0, baseLength);
        const sequence = [...base, ...base].slice(0, patternLength);
        return { sequence, correctAnswer: base[0], pattern: "Repeating sequence" };
      },
      // Alternating pattern
      () => {
        const shape1 = SHAPES[0];
        const shape2 = SHAPES[1];
        const sequence = Array.from({ length: patternLength }, (_, i) =>
          i % 2 === 0 ? shape1 : shape2
        );
        return {
          sequence,
          correctAnswer: patternLength % 2 === 0 ? shape1 : shape2,
          pattern: "Alternating pattern"
        };
      },
      // Sequential progression
      () => {
        const sequence = SHAPES.slice(0, patternLength);
        const correctAnswer = SHAPES[patternLength] || allShapes[patternLength] || SHAPES[0];
        return { sequence, correctAnswer, pattern: "Sequential progression" };
      }
    ];

    const availablePatterns = patterns.slice(0, Math.min(complexity, patterns.length));
    const generator = availablePatterns[Math.floor(Math.random() * availablePatterns.length)];
    const result = generator();
    const options = buildOptions(result.correctAnswer, result.sequence, allShapes);

    return { sequence: result.sequence, options, correctAnswer: result.correctAnswer, pattern: result.pattern };
  };

  const generateNumberPattern = (): Puzzle => {
    const patternLength = Math.min(sequenceLength, 6);

    const patterns = [
      // Arithmetic sequence
      () => {
        const start = Math.floor(Math.random() * 5) + 1;
        const diff = Math.max(1, complexity);
        const sequence = Array.from({ length: patternLength }, (_, i) => (start + i * diff).toString());
        return {
          sequence,
          correctAnswer: (start + patternLength * diff).toString(),
          pattern: "Arithmetic sequence"
        };
      },
      // Fibonacci-like
      () => {
        const fib = [1, 1];
        for (let i = 2; i < patternLength; i++) fib.push(fib[i - 1] + fib[i - 2]);
        return {
          sequence: fib.map(String),
          correctAnswer: (fib[fib.length - 1] + fib[fib.length - 2]).toString(),
          pattern: "Fibonacci sequence"
        };
      },
      // Skip counting
      () => {
        const start = 2;
        const step = complexity + 1;
        const sequence = Array.from({ length: patternLength }, (_, i) => (start + i * step).toString());
        return {
          sequence,
          correctAnswer: (start + patternLength * step).toString(),
          pattern: complexity > 1 ? "Skip counting" : "Even numbers"
        };
      }
    ];

    const availablePatterns = patterns.slice(0, Math.min(complexity, patterns.length));
    const generator = availablePatterns[Math.floor(Math.random() * availablePatterns.length)];
    const result = generator();
    const correctNum = parseInt(result.correctAnswer);

    // FIX: Generate robust wrong options that always produce 3 total choices
    const usedNums = new Set(result.sequence.map(Number));
    usedNums.add(correctNum);
    const wrongCandidates: string[] = [];
    for (let delta = 1; wrongCandidates.length < 4; delta++) {
      if (!usedNums.has(correctNum + delta) && correctNum + delta > 0) {
        wrongCandidates.push((correctNum + delta).toString());
        usedNums.add(correctNum + delta);
      }
      if (!usedNums.has(correctNum - delta) && correctNum - delta > 0) {
        wrongCandidates.push((correctNum - delta).toString());
        usedNums.add(correctNum - delta);
      }
    }
    const wrong = wrongCandidates.slice(0, 2);
    const options = [result.correctAnswer, ...wrong].sort(() => Math.random() - 0.5);

    return {
      sequence: result.sequence,
      options,
      correctAnswer: result.correctAnswer,
      pattern: result.pattern
    };
  };

  const generateNewPuzzle = () => {
    const puzzle = Math.random() > 0.5 ? generateShapePattern() : generateNumberPattern();
    setCurrentPuzzle(puzzle);
    setSelectedAnswer(null);
    setShowResult(false);
  };

  useEffect(() => {
    generateNewPuzzle();
  }, [currentRound]);

  const handleAnswerSelect = (answer: string) => {
    if (showResult) return;
    setSelectedAnswer(answer);
    const correct = answer === currentPuzzle?.correctAnswer;
    setIsCorrect(correct);
    setShowResult(true);
    if (correct) setCorrectAnswers(prev => prev + 1);
  };

  const handleNext = () => {
    if (currentRound >= totalRounds) {
      setGameComplete(true);
      const timeBonus = Math.max(0, 300 - Math.floor((Date.now() - gameStartTimeRef.current) / 1000));
      const score = correctAnswers * 100 + timeBonus;
      // FIX: pass real elapsed duration instead of hardcoded 180
      const duration = Math.round((Date.now() - gameStartTimeRef.current) / 1000);
      onGameComplete(score, correctAnswers, totalRounds, duration, difficultyData);
    } else {
      setCurrentRound(prev => prev + 1);
    }
  };

  const restartGame = () => {
    gameStartTimeRef.current = Date.now();
    setCurrentRound(1);
    setCorrectAnswers(0);
    setGameComplete(false);
    generateNewPuzzle();
  };

  if (!difficultyData) {
    return (
      <Card className="w-full max-w-2xl mx-auto premium-shadow">
        <CardContent className="flex items-center justify-center p-12">
          <div className="text-center space-y-4">
            <div className="text-4xl">🧠</div>
            <p className="text-muted-foreground">Loading adaptive difficulty...</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!currentPuzzle) {
    return (
      <Card className="w-full max-w-2xl mx-auto premium-shadow">
        <CardContent className="p-8 text-center text-muted-foreground">Loading...</CardContent>
      </Card>
    );
  }

  return (
    <Card className="w-full max-w-2xl mx-auto premium-shadow">
      <CardHeader className="text-center">
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <i className="fas fa-brain text-primary"></i>
            Logic Puzzle
          </div>
          <Button variant="ghost" onClick={onClose} data-testid="button-close-logic-game">
            <i className="fas fa-times"></i>
          </Button>
        </CardTitle>
        <div className="flex justify-center gap-8 text-sm text-muted-foreground">
          <div data-testid="logic-round">Round: {currentRound}/{totalRounds}</div>
          <div data-testid="logic-score">Correct: {correctAnswers}</div>
        </div>
      </CardHeader>
      <CardContent>
        {gameComplete ? (
          <LogicResultScreen
            correct={correctAnswers}
            total={totalRounds}
            onPlayAgain={restartGame}
            onClose={onClose}
          />
        ) : (
          <div className="space-y-6">
            <div className="text-center">
              <h3 className="text-xl font-semibold mb-4">What comes next in this sequence?</h3>

              {/* Sequence Display */}
              <div className="flex items-center justify-center gap-4 mb-6">
                {currentPuzzle.sequence.map((item, index) => (
                  <div
                    key={index}
                    className="w-16 h-16 flex items-center justify-center bg-muted rounded-lg border-2 border-border text-2xl font-bold"
                  >
                    {item}
                  </div>
                ))}
                <div className="text-2xl text-muted-foreground mx-2">→</div>
                <div className="w-16 h-16 flex items-center justify-center border-2 border-dashed border-primary rounded-lg text-primary text-xl">
                  ?
                </div>
              </div>

              {/* Options */}
              <div className="flex justify-center gap-4 mb-6">
                {currentPuzzle.options.map((option, index) => (
                  <button
                    key={index}
                    onClick={() => handleAnswerSelect(option)}
                    className={`w-16 h-16 flex items-center justify-center rounded-lg border-2 transition-all text-2xl font-bold
                      ${selectedAnswer === option
                        ? showResult
                          ? option === currentPuzzle.correctAnswer
                            ? 'bg-green-100 border-green-500 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                            : 'bg-red-100 border-red-500 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                          : 'bg-primary text-white border-primary'
                        : 'bg-muted hover:bg-muted/80 border-border hover:border-primary/50'
                      }
                      ${showResult && option === currentPuzzle.correctAnswer && selectedAnswer !== option
                        ? 'bg-green-100 border-green-500 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                        : ''
                      }
                    `}
                    disabled={showResult}
                    data-testid={`logic-option-${index}`}
                  >
                    {option}
                  </button>
                ))}
              </div>

              {/* Result */}
              {showResult && (
                <div className="space-y-4">
                  <div className={`text-lg font-semibold ${isCorrect ? 'text-green-600' : 'text-red-600'}`}>
                    {isCorrect ? '✅ Correct!' : '❌ Incorrect'}
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Pattern: {currentPuzzle.pattern}
                  </p>
                  <GradientButton onClick={handleNext} data-testid="button-next-logic">
                    {currentRound >= totalRounds ? 'Finish Game' : 'Next Puzzle'}
                  </GradientButton>
                </div>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
